/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package goldenbug;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;
import java.util.Map.Entry;
import javax.swing.BoxLayout;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author alex
 */
public class Interactivo extends javax.swing.JFrame {

    /**
     * Creates new form Interactivo
     */
    public Interactivo() {
        initComponents();
        this.letras=new ArrayList();
        this.goldenBug=new GoldenBug();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        textoCifrado = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textoDescifrado = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        correspondencias = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        crearTablero = new javax.swing.JButton();
        sustituir = new javax.swing.JButton();
        ngrams = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        calcularFrecuencias = new javax.swing.JButton();
        pares = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textoCifrado.setColumns(20);
        textoCifrado.setLineWrap(true);
        textoCifrado.setRows(5);
        textoCifrado.setWrapStyleWord(true);
        jScrollPane1.setViewportView(textoCifrado);

        jLabel1.setText("Texto cifrado");

        textoDescifrado.setEditable(false);
        textoDescifrado.setColumns(20);
        textoDescifrado.setLineWrap(true);
        textoDescifrado.setRows(5);
        textoDescifrado.setWrapStyleWord(true);
        jScrollPane2.setViewportView(textoDescifrado);

        jLabel2.setText("Texto descifrado");

        correspondencias.setLayout(new java.awt.GridBagLayout());

        jLabel3.setText("Correspondencias");

        crearTablero.setText("Crear tablero");
        crearTablero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                crearTableroMouseReleased(evt);
            }
        });
        crearTablero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearTableroActionPerformed(evt);
            }
        });

        sustituir.setText("Aplicar sustituciones");
        sustituir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                sustituirMouseReleased(evt);
            }
        });
        sustituir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sustituirActionPerformed(evt);
            }
        });

        jLabel4.setText("N-gramas");

        calcularFrecuencias.setText("Calcular frecuencias");
        calcularFrecuencias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                calcularFrecuenciasMouseReleased(evt);
            }
        });

        pares.setText("Calcular frecuencias pares ");
        pares.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                paresMouseReleased(evt);
            }
        });
        pares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(316, 316, 316))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(correspondencias, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(254, 254, 254)
                                .addComponent(jLabel2))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ngrams, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(calcularFrecuencias, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(pares))
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(98, 98, 98))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(crearTablero, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(sustituir, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(crearTablero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(correspondencias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sustituir, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ngrams, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(calcularFrecuencias)
                    .addComponent(pares))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void crearTableroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearTableroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_crearTableroActionPerformed

    private void crearTableroMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearTableroMouseReleased
        this.correspondencias.removeAll();
        Map<Character,Character> mapTable= new HashMap();
        String textoCifrado=this.textoCifrado.getText().toLowerCase().replaceAll("[^A-Za-z]+", "");
        GridBagConstraints cons= new GridBagConstraints();
        cons.gridx=0;
        cons.gridy=0;
        cons.weightx=1;
        cons.weighty=1;
        for(int i=0;i<textoCifrado.length();i++){
            char c=textoCifrado.charAt(i);
            if(!mapTable.containsKey(c)){
                mapTable.put(c,'*');
                JTextField letra=new JTextField();
                CustomTextfield traduccion=new CustomTextfield(letra,mapTable);
                letras.add(traduccion);
                traduccion.setPreferredSize(new Dimension(25,25));
                letra.setEditable(false);
                letra.setPreferredSize(new Dimension(25,25));
                letra.setText(""+c);
                
                this.correspondencias.add(letra,cons);
                cons.gridx++;
                this.correspondencias.add(traduccion,cons);
                cons.gridy++;
                cons.gridx=0;
            }
        }
       
        this.correspondencias.repaint();
        this.correspondencias.revalidate();
        this.tableMap=mapTable;
         sustituir();
        
    }//GEN-LAST:event_crearTableroMouseReleased

    private void sustituirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sustituirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sustituirActionPerformed

    private void sustituirMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sustituirMouseReleased
        sustituir();
    }//GEN-LAST:event_sustituirMouseReleased

    private void calcularFrecuenciasMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calcularFrecuenciasMouseReleased
        // TODO add your handling code here:
        int ngram=Integer.valueOf(this.ngrams.getText());
        Map<String,Double> map=this.goldenBug.reduce(this.goldenBug.sortNgram(this.goldenBug.calcularFrecuenciasNgramas(textoCifrado.getText().toLowerCase().replaceAll("[^A-Za-z]+", ""), ngram)));
        
        
        
        JFrame frame = new JFrame("Frecuencias");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setSize(1350, 1300);
        
        BarChart bc = new BarChart(map, "Frecuencias de "+ngram+"-gramas",true);
        
        JPanel listPane=new JPanel();
        frame.setLayout(new BoxLayout(frame.getContentPane(),BoxLayout.Y_AXIS));
        frame.add(bc);
        if(ngram<=3){
            BarChart freqIngles=new BarChart(this.goldenBug.getNGramFrecuencias(ngram),
                    "Frecuencias de "+ngram+"-gramas en ingles",false);
            frame.add(freqIngles);
        }
        frame.setVisible(true);
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_calcularFrecuenciasMouseReleased

    private void paresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paresActionPerformed

    private void paresMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paresMouseReleased
        // TODO add your handling code here:
        Map<String,Double> map=this.goldenBug.reduce(this.goldenBug.sortNgram(this.goldenBug.calcularFrecuenciasRepes(textoCifrado.getText().replace("[^a-zA-Z- ]",""))));
        JFrame frame = new JFrame("Frecuencia de 2-gramas repetidos");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setSize(1350, 1300);
        
        BarChart bc = new BarChart(map, "Frecuencias de 2-gramas repetidos",true);
        
        JPanel listPane=new JPanel();
        frame.setLayout(new BoxLayout(frame.getContentPane(),BoxLayout.Y_AXIS));
        frame.add(bc);
        frame.add(new BarChart(this.goldenBug.getRepes(),"Pares de letras repetidas mas comunes en ingles",false));
        frame.setVisible(true);
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_paresMouseReleased
    
    
    public void sustituir(){
        String sustituido=this.textoCifrado.getText().toLowerCase();
        for(CustomTextfield cT:letras){
            cT.updateMap();
        }
        Iterator<Map.Entry<Character,Character>> iterator =this.tableMap.entrySet().iterator();
        while(iterator.hasNext()){
            Entry<Character,Character> entry=iterator.next();
            sustituido=sustituido.replace(entry.getKey(),entry.getValue());
        }
        this.textoDescifrado.setText(sustituido);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interactivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interactivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interactivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interactivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interactivo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calcularFrecuencias;
    private javax.swing.JPanel correspondencias;
    private javax.swing.JButton crearTablero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField ngrams;
    private javax.swing.JButton pares;
    private javax.swing.JButton sustituir;
    private javax.swing.JTextArea textoCifrado;
    private javax.swing.JTextArea textoDescifrado;
    // End of variables declaration//GEN-END:variables
    private Map<Character,Character> tableMap;
    private ArrayList<CustomTextfield> letras;
    private GoldenBug goldenBug;
}
